=== VHAINNOVATIONS/Hazardous-Pharmaceuticals/PS_PPS_Dev/PS_PPS_interface/etc/xml/schema/drug/drugaccountability/drugAccountabilityRequest.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="gov/va/med/pharmacy/peps/external/common/vo/inbound/drug/drugaccountability/request"
    xmlns="gov/va/med/pharmacy/peps/external/common/vo/inbound/drug/drugaccountability/request"
    xmlns:common="gov/va/med/pharmacy/peps/external/common/vo/outbound/common"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xsd:import
        namespace="gov/va/med/pharmacy/peps/external/common/vo/outbound/common"
        schemaLocation="../../common.xsd" />

    <xsd:element name="drugAccountabilityRequest">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    ref="requestAdd"
                    minOccurs="0"
                    maxOccurs="unbounded" />
                <xsd:element
                    ref="requestUpdate"
                    minOccurs="0"
                    maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>


    <xsd:element name="requestAdd">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="ndc"
                    type="ndcField"
                    minOccurs="1"
                    maxOccurs="1" />

                <xsd:element
                    name="vuid"
                    type="xsd:integer"
                    minOccurs="1"
                    maxOccurs="1" />

                <xsd:element
                    name="orderUnit"
                    type="xsd:string"
                    minOccurs="1"
                    maxOccurs="1" />

                <xsd:element
                    name="pricePerDispenseUnit"
                    type="xsd:double"
                    minOccurs="1"
                    maxOccurs="1" />

                <xsd:element
                    name="pricePerOrderUnit"
                    type="xsd:double"
                    minOccurs="1"
                    maxOccurs="1" />

                <xsd:element
                    ref="addSynonymFields"
                    minOccurs="0"
                    maxOccurs="1" />
                <xsd:element
                    ref="addNDCFields"
                    minOccurs="0"
                    maxOccurs="1" />
                <xsd:element
                    ref="addProductFields"
                    minOccurs="0"
                    maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="requestUpdate">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="ndc"
                    type="ndcField"
                    minOccurs="1"
                    maxOccurs="1" />

                <xsd:element
                    name="vuid"
                    type="xsd:integer"
                    minOccurs="1"
                    maxOccurs="1" />

                <xsd:element
                    ref="updateSynonymFields"
                    minOccurs="0"
                    maxOccurs="1" />
                <xsd:element
                    ref="updateNDCFields"
                    minOccurs="0"
                    maxOccurs="1" />
                <xsd:element
                    ref="updateProductFields"
                    minOccurs="0"
                    maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="addSynonymFields">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="vsn"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="vendor"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="dispenseUnitsPerOrderUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="updateSynonymFields">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="vsn"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="vendor"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="orderUnit"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="pricePerOrderUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="dispenseUnitsPerOrderUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="pricePerDispenseUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="addNDCFields">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="vsn"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="vendor"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="dispenseUnitsPerOrderUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="otcRXIndicator"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="manufacturer"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="updateNDCFields">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="vsn"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="vendor"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="orderUnit"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="pricePerOrderUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="dispenseUnitsPerOrderUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="pricePerDispenseUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="otcRXIndicator"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="manufacturer"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="addProductFields">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="dispenseUnitPerOrderUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="currentInventory"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="ifcapItemNumber"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="updateProductFields">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="orderUnit"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="pricePerOrderUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="dispenseUnitsPerOrderUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="pricePerDispenseUnit"
                    type="xsd:double"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="currentInventory"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="1" />

                <xsd:element
                    name="ifcapItemNumber"
                    type="xsd:string"
                    minOccurs="0"
                    maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="ndcField">
        <xsd:restriction base="xsd:string">
            <!-- xxxxx-xxxx-xx (12 digit NDC)-->
            <xsd:pattern value="\d{6}-\d{4}-\d{2}" />
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== VHAINNOVATIONS/Hazardous-Pharmaceuticals/PS_PPS_Dev/PS_PPS_interface/etc/xml/document/drug/drugaccountability/DrugAccountabilityOneNew.xml
<?xml version="1.0" encoding="UTF-8"?>
<drugAccountabilityRequest
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="gov/va/med/pharmacy/peps/external/common/vo/inbound/drug/drugaccountability/request ../../../schema/drug/drugaccountability/DrugAccountabilityRequest.xsd "
    xmlns="gov/va/med/pharmacy/peps/external/common/vo/inbound/drug/drugaccountability/request">
    <requestAdd>
        <ndc>002669-9010-99</ndc>
        <vuid>4002698</vuid>
        <orderUnit>EA</orderUnit>
        <pricePerDispenseUnit>10.01</pricePerDispenseUnit>
        <pricePerOrderUnit>10.02</pricePerOrderUnit>
        <addSynonymFields>
            <vsn>VSN10</vsn>
            <vendor>McKesson Corporation</vendor>
            <dispenseUnitsPerOrderUnit>10.03</dispenseUnitsPerOrderUnit>
        </addSynonymFields>
        <addNDCFields>
            <vsn>VSN10</vsn>
            <vendor>McKesson Corporation</vendor>
            <dispenseUnitsPerOrderUnit>10.04</dispenseUnitsPerOrderUnit>
            <otcRXIndicator>0</otcRXIndicator>
            <manufacturer>EMD</manufacturer>
        </addNDCFields>
        <addProductFields>
            <dispenseUnitPerOrderUnit>10.05</dispenseUnitPerOrderUnit>
            <currentInventory>10</currentInventory>
            <ifcapItemNumber>45</ifcapItemNumber>
        </addProductFields>
    </requestAdd>
</drugAccountabilityRequest>

=== VHAINNOVATIONS/Hazardous-Pharmaceuticals/PS_PPS_Dev/PS_PPS_interface/etc/xml/document/drug/drugaccountability/DrugAccountabilityMultipleEntries.xml
<?xml version="1.0" encoding="UTF-8"?>
<drugAccountabilityRequest
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="gov/va/med/pharmacy/peps/external/common/vo/inbound/drug/drugaccountability/request ../../../schema/drug/drugaccountability/DrugAccountabilityRequest.xsd "
    xmlns="gov/va/med/pharmacy/peps/external/common/vo/inbound/drug/drugaccountability/request">
    <requestAdd>
        <ndc>024322-3660-93</ndc>
        <vuid>4002698</vuid>
        <orderUnit>EA</orderUnit>
        <pricePerDispenseUnit>80.01</pricePerDispenseUnit>
        <pricePerOrderUnit>80.02</pricePerOrderUnit>
        <addSynonymFields>
            <vsn>VSN80</vsn>
            <vendor>McKesson Corporation</vendor>
            <dispenseUnitsPerOrderUnit>80.03</dispenseUnitsPerOrderUnit>
        </addSynonymFields>
        <addNDCFields>
            <vsn>VSN80</vsn>
            <vendor>McKesson Corporation</vendor>
            <dispenseUnitsPerOrderUnit>80.03</dispenseUnitsPerOrderUnit>
            <otcRXIndicator>0</otcRXIndicator>
            <manufacturer>EMD</manufacturer>
        </addNDCFields>
        <addProductFields>
            <dispenseUnitPerOrderUnit>80.03</dispenseUnitPerOrderUnit>
            <currentInventory>80</currentInventory>
            <ifcapItemNumber>80</ifcapItemNumber>
        </addProductFields>
    </requestAdd>
    
    <requestUpdate>
        <ndc>002669-9010-99</ndc>
        <vuid>4002698</vuid>
        <updateSynonymFields>
            <vsn>VSN81</vsn>
            <vendor>McKesson Corporation</vendor>
            <orderUnit>BT</orderUnit>
            <pricePerOrderUnit>81.02</pricePerOrderUnit>
            <dispenseUnitsPerOrderUnit>81.03</dispenseUnitsPerOrderUnit>
            <pricePerDispenseUnit>81.01</pricePerDispenseUnit>
        </updateSynonymFields>
        <updateNDCFields>
            <vsn>VSN81</vsn>
            <vendor>McKesson Corporation</vendor>
            <orderUnit>BT</orderUnit>
            <pricePerOrderUnit>81.02</pricePerOrderUnit>
            <dispenseUnitsPerOrderUnit>81.03</dispenseUnitsPerOrderUnit>
            <pricePerDispenseUnit>81.01</pricePerDispenseUnit>
            <otcRXIndicator>0</otcRXIndicator>
            <manufacturer>AMER RED CROSS</manufacturer>
        </updateNDCFields>
        <updateProductFields>
            <orderUnit>BT</orderUnit>
            <pricePerOrderUnit>81.02</pricePerOrderUnit>
            <dispenseUnitsPerOrderUnit>81.03</dispenseUnitsPerOrderUnit>
            <pricePerDispenseUnit>81.01</pricePerDispenseUnit>
            <currentInventory>81</currentInventory>
            <ifcapItemNumber>81</ifcapItemNumber>
        </updateProductFields>
    </requestUpdate>
</drugAccountabilityRequest>

=== VHAINNOVATIONS/Hazardous-Pharmaceuticals/PS_PPS_Dev/PS_PPS_interface/etc/xml/document/drug/drugaccountability/DrugAccountabilityMultipleUpdates.xml
<?xml version="1.0" encoding="UTF-8"?>
<drugAccountabilityRequest
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="gov/va/med/pharmacy/peps/external/common/vo/inbound/drug/drugaccountability/request ../../../schema/drug/drugaccountability/DrugAccountabilityRequest.xsd "
    xmlns="gov/va/med/pharmacy/peps/external/common/vo/inbound/drug/drugaccountability/request">
    <requestUpdate>
        <ndc>043254-1234-10</ndc>
        <vuid>4002698</vuid>
        <updateSynonymFields>
            <vsn>VSN-30</vsn>
            <vendor>CYGEN PHARMACY SUPPLIES</vendor>
            <orderUnit>BT</orderUnit>
            <pricePerOrderUnit>130.02</pricePerOrderUnit>
            <dispenseUnitsPerOrderUnit>130.03</dispenseUnitsPerOrderUnit>
            <pricePerDispenseUnit>130.01</pricePerDispenseUnit>
        </updateSynonymFields>
        <updateNDCFields>
            <vsn>VSN-30</vsn>
            <vendor>CYGEN PHARMACY SUPPLIES</vendor>
            <orderUnit>BT</orderUnit>
            <pricePerOrderUnit>130.02</pricePerOrderUnit>
            <dispenseUnitsPerOrderUnit>130.03</dispenseUnitsPerOrderUnit>
            <pricePerDispenseUnit>130.01</pricePerDispenseUnit>
            <otcRXIndicator>0</otcRXIndicator>
            <manufacturer>AMER RED CROSS</manufacturer>
        </updateNDCFields>
        <updateProductFields>
            <orderUnit>BT</orderUnit>
            <pricePerOrderUnit>130.02</pricePerOrderUnit>
            <dispenseUnitsPerOrderUnit>130.03</dispenseUnitsPerOrderUnit>
            <pricePerDispenseUnit>130.01</pricePerDispenseUnit>
            <currentInventory>130</currentInventory>
            <ifcapItemNumber>130</ifcapItemNumber>
        </updateProductFields>
    </requestUpdate>
    
    <requestUpdate>
        <ndc>043254-1234-11</ndc>
        <vuid>4002698</vuid>
        <updateSynonymFields>
            <vsn>VSN-31</vsn>
            <vendor>CYGEN PHARMACY SUPPLIES</vendor>
            <orderUnit>BT</orderUnit>
            <pricePerOrderUnit>131.02</pricePerOrderUnit>
            <dispenseUnitsPerOrderUnit>131.03</dispenseUnitsPerOrderUnit>
            <pricePerDispenseUnit>131.01</pricePerDispenseUnit>
        </updateSynonymFields>
    </requestUpdate>
    
    <requestUpdate>
        <ndc>043254-1234-12</ndc>
        <vuid>4002698</vuid>
        <updateNDCFields>
            <vsn>VSN-32</vsn>
            <vendor>CYGEN PHARMACY SUPPLIES</vendor>
            <orderUnit>BT</orderUnit>
            <pricePerOrderUnit>132.02</pricePerOrderUnit>
            <dispenseUnitsPerOrderUnit>132.03</dispenseUnitsPerOrderUnit>
            <pricePerDispenseUnit>132.01</pricePerDispenseUnit>
            <otcRXIndicator>0</otcRXIndicator>
            <manufacturer>AMER RED CROSS</manufacturer>
        </updateNDCFields>
    </requestUpdate>
    
    <requestUpdate>
        <ndc>043254-1234-13</ndc>
        <vuid>4002698</vuid>
        <updateProductFields>
            <orderUnit>BT</orderUnit>
            <pricePerOrderUnit>133.02</pricePerOrderUnit>
            <dispenseUnitsPerOrderUnit>133.03</dispenseUnitsPerOrderUnit>
            <pricePerDispenseUnit>133.01</pricePerDispenseUnit>
            <currentInventory>133</currentInventory>
            <ifcapItemNumber>133</ifcapItemNumber>
        </updateProductFields>
    </requestUpdate>
</drugAccountabilityRequest>
