=== VHAINNOVATIONS/Hazardous-Pharmaceuticals/PS_PPS_Dev/PS_PPS_interface/etc/xml/schema/migration/drugMigrationResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="gov/va/med/pharmacy/peps/external/common/vo/inbound/migration/data/response"
     
    targetNamespace="gov/va/med/pharmacy/peps/external/common/vo/inbound/migration/data/response" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified">

    <xsd:element name="drugMigrationResponse">
        <xsd:complexType>
            <xsd:sequence>
            	<xsd:element name="responseHeader" type="responseHeaderType" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="invalidRequest" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                <xsd:element name="vaProduct" type="vaProductFieldsType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="drugIngredients" type="drugIngredientsFieldsType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="vaGenericName" type="vaGenericNameFieldsType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="vaDrugClass" type="vaDrugClassFieldsType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="drugUnits" type="drugUnitsFieldType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="vaDispenseUnit" type="vaDispenseUnitFieldType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="dosageForm" type="dosageFormFieldType" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="responseHeaderType">
        <xsd:sequence>
            <xsd:element name="endOfFile" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="vaProductFieldsType">
        <xsd:sequence>
            <xsd:element name="ndfProductIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="vaGenericName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="dosageForm" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="strength" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="units" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nationalFormularyName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="vaPrintName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="vaProductIdentifier" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="transmitToCmop" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="vaDispenseUnit" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="gcnSeqNo" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="activeIngredients" type="activeIngredients" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="primaryVaDrugClass" type="drugClassRow" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="nationalFormularyIndicator" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="csFederalSchedule" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="singleMultiSourceProduct" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="inactivationDate" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="overrideDfDoseChkExclusion" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="excludeDrugDrugInteraction" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="createPossibleDosage" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="productPackage" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="masterEntryForVuid" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="vuid" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="effectiveDateTime" type="effectiveDateTime" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="fdaMedGuide" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="serviceCode" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="possibleDosagesToCreate" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="drugIngredientsFieldsType">
        <xsd:sequence>
            <xsd:element name="drugIngredientsIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="primaryIngredient" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="inactivationDate" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="masterEntryForVuid" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="vuid" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="effectiveDateTime" type="effectiveDateTime" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="vaGenericNameFieldsType">
        <xsd:sequence>
            <xsd:element name="vaGenericIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="inactivationDate" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="masterEntryForVuid" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="vuid" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="effectiveDateTime" type="effectiveDateTime" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="vaDrugClassFieldsType">
        <xsd:sequence>
            <xsd:element name="vaDrugClassIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="code" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="classification" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="parentClass" type="drugClassRow" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="type" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="masterEntryForVuid" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="vuid" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="effectiveDateTime" type="effectiveDateTime" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="drugClassRow">
        <xsd:sequence>
            <xsd:element name="vaDrugClassIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="code" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="classification" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="drugUnitsFieldType">
        <xsd:sequence>
            <xsd:element name="drugUnitsIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="inactivationDate" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="vaDispenseUnitFieldType">
        <xsd:sequence>
            <xsd:element name="dispenseUnitsIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="inactivationDate" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="dosageFormFieldType">
        <xsd:sequence>
            <xsd:element name="dosageFormIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="inactivationDate" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="units" type="units" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="dispenseUnitsPerDose" type="dispenseUnitsPerDose" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="excludeFromDosageChecks" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="activeIngredients">
        <xsd:sequence>
            <xsd:element name="activeIngredientIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="ingredientName" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="strength" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="units" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="effectiveDateTime">
        <xsd:sequence>
            <xsd:element name="effectiveDateTime" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="status" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="dispenseUnitsPerDose">
        <xsd:sequence>
            <xsd:element name="dispenseUnitsPerDoseIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="dispenseUnitsPerDose" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="package" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="units">
        <xsd:sequence>
            <xsd:element name="unitsIen" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="units" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="package" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== VHAINNOVATIONS/Hazardous-Pharmaceuticals/PS_PPS_Dev/PS_PPS_interface/etc/xml/document/migration/response/drugUnits/DrugUnitMigrationResponse.xml
<?xml version="1.0" encoding="utf-8" ?>
<drugMigrationResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema"
xsi:schemaLocation="gov/va/med/pharmacy/peps/external/common/vo/inbound/migration/data/response ../../../schema/migration/drugMigrationResponse.xsd"
xmlns="gov/va/med/pharmacy/peps/external/common/vo/inbound/migration/data/response">
<responseHeader><endOfFile>0</endOfFile></responseHeader>
<drugUnits>
<drugUnitsIen>1</drugUnitsIen><name>0.5ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>5</drugUnitsIen><name>GM/1CC</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>7</drugUnitsIen><name>GM/2ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>12</drugUnitsIen><name>5ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>15</drugUnitsIen><name>GR/5ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>16</drugUnitsIen><name>GR/ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>18</drugUnitsIen><name>MEQ/10ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>28</drugUnitsIen><name>MG/25ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>40</drugUnitsIen><name>UNT/10M</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>41</drugUnitsIen><name>UNT/2ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>45</drugUnitsIen><name>%/0.5ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>46</drugUnitsIen><name>%MIN</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>50</drugUnitsIen><name>0.3ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>51</drugUnitsIen><name>0.6ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>52</drugUnitsIen><name>10ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>54</drugUnitsIen><name>20ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>55</drugUnitsIen><name>2ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>56</drugUnitsIen><name>3MG</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>57</drugUnitsIen><name>50ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>58</drugUnitsIen><name>5MG/ML</name><inactivationDate>20000830</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>59</drugUnitsIen><name>6M/60ML</name><inactivationDate>20000830</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>60</drugUnitsIen><name>7.5ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>61</drugUnitsIen><name>z</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>62</drugUnitsIen><name>BAG</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>63</drugUnitsIen><name>BTL</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>66</drugUnitsIen><name>GM/4ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>72</drugUnitsIen><name>GM/CAP</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>73</drugUnitsIen><name>GM/CTR</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>76</drugUnitsIen><name>GM/SML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>77</drugUnitsIen><name>GM/SUS</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>80</drugUnitsIen><name>GR/10ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>81</drugUnitsIen><name>GR/20ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>82</drugUnitsIen><name>GR/FLO</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>83</drugUnitsIen><name>I.U./ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>84</drugUnitsIen><name>M</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>86</drugUnitsIen><name>MCG/2ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>87</drugUnitsIen><name>MCG/CTR</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>89</drugUnitsIen><name>MCG/UNT</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>91</drugUnitsIen><name>MEG/ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>93</drugUnitsIen><name>MEQ/4GM</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>96</drugUnitsIen><name>MEQ/AMP</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>98</drugUnitsIen><name>MEQ/OZ</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>100</drugUnitsIen><name>MEQ/TBL</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>102</drugUnitsIen><name>MG/1.8ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>104</drugUnitsIen><name>MG/12.6ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>105</drugUnitsIen><name>MG/16ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>106</drugUnitsIen><name>MG/17GM</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>109</drugUnitsIen><name>MG/40ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>115</drugUnitsIen><name>MG/8ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>119</drugUnitsIen><name>MG/CTR</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>120</drugUnitsIen><name>MG/FLO</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>121</drugUnitsIen><name>MG/JML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>123</drugUnitsIen><name>MG/PAD</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>124</drugUnitsIen><name>MG/PEL</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>126</drugUnitsIen><name>MG/TUBE</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>127</drugUnitsIen><name>MH</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>134</drugUnitsIen><name>MIL/10M</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>135</drugUnitsIen><name>MIL/2ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>138</drugUnitsIen><name>MIN/AMP</name><inactivationDate>20060815</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>139</drugUnitsIen><name>MIN/ML</name><inactivationDate>20060815</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>140</drugUnitsIen><name>ML/.5ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>141</drugUnitsIen><name>ML/MG</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>142</drugUnitsIen><name>ML/UNT</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>148</drugUnitsIen><name>SUPP</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>149</drugUnitsIen><name>U/0.5ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>150</drugUnitsIen><name>U/1.2ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>152</drugUnitsIen><name>UNT/2.5ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>154</drugUnitsIen><name>UNT/DOS</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>155</drugUnitsIen><name>UNT/MG</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>160</drugUnitsIen><name>DR</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>161</drugUnitsIen><name>EA</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>162</drugUnitsIen><name>FLO</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>163</drugUnitsIen><name>GAL</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>164</drugUnitsIen><name>LITER</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>165</drugUnitsIen><name>LB</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>166</drugUnitsIen><name>MIN</name><inactivationDate>20060815</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>169</drugUnitsIen><name>PT</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>170</drugUnitsIen><name>TRACE</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
<drugUnitsIen>278</drugUnitsIen><name>/5ML</name><inactivationDate>20080219</inactivationDate>
</drugUnits>
<drugUnits>
